# Secrets para credenciales sensibles
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: arresto-system
type: Opaque
stringData:
  POSTGRES_USER: admin
  POSTGRES_PASSWORD: "YourSecurePassword123!"  # CAMBIAR EN PRODUCCIÓN
  POSTGRES_DB: arrest_registry
---
apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: arresto-system
type: Opaque
stringData:
  JWT_SECRET: "your-super-secret-jwt-key-change-this-in-production"  # CAMBIAR
  DB_PASSWORD: "YourSecurePassword123!"  # Debe coincidir con postgres-secret
